
---
title: "Prophet"
output: html_document
---
Model

$y(t)  = g(t) + s(t) + h(t) + \epsilon_t$

Use logistic saturating growth curve:

$g(t) = \frac{C}{1 + \exp{(−k (t−m))}}$

Where $C$ is total capacity, $k$ is growth rate. C is not supposed to be parameter, so cannot fix shape arbitrarily.


Representation chosen is
$(k + \sum_{l<=j} \delta_l  a_l(t)) (t − m − \sum_{l<=j} \gamma_l  a_l(t))$

Where $a_l(t) = \chi \left(t \ge s_l \right)$.
$\gamma$ is chosen to ensure continuity at changepoints:

$(k + \sum_{l<=j} a_l(t)\delta_l  ) (s_j − m − \sum_{l<=j}  a_l(t) \gamma_l ) =  (k + \sum_{l<j} a_l(t) \delta_l ) (s_j − m − \sum_{l<j} a_l(t) \gamma_l  )$

Solving for $\gamma$ we get an iterative equation for $\gamma$ in terms of previous values of $gamma$.
For linear trend, modified slightly
$(k + \sum_{l<=j} a_l(t) \delta_l  ) t  +  m + \sum_{l<=j}a_l(t) \gamma_l  ) $

why use $k(t - m)$ representation  and associated piecewise format, instead of $kt + m_1+ \sum_{l \le j} \delta_l \max(t−s_l, 0)$ this is linear in all parameters and does not require calculation of $\gamma$

Sparse prior on $\delta$, $\delta \sim \text{Laplace}(0, \tau)$

### Seasonality

$s(t) = \sum_{n=1}^N\left( a_n \cos \frac{2\pi n t}{P} +  b_n \sin \frac{2\pi n t }{P} \right)$

$\beta \sim \text{Normal}(0, \sigma^2)$


Truncating at N, imposes low pass filter, choose 10 for annual and 3 for weekly.  

Holidays use dummy variables  impose $k \sim \text{Normal}(0, \nu^2)$.

# Model Call
| Value | Type| Description| 
|-------| ----| -----------|
|  df   | \|ds\|  y\| category\| | (optional) Dataframe containing the history. Must have columns ds (date type) and y, the time series. If growth is logistic, then df must also have a column cap that specifies the capacity at each ds. |
|growth| 'linear' \|'logistic'| to specify a linear or logistic trend.|
|changepoints| |Vector of dates at which to include potential changepoints. If not specified, potential changepoints are selected automatically. (common set of changepoints) to support interpolation|
|n.changepoints| integer| Number of potential changepoints to include. Not used if input `changepoints` is supplied. If `changepoints` is not supplied,then n.changepoints potential changepoints are selected uniformly from the first `changepoint.range` proportion of df$ds. |
|changepoint.range| | Proportion of history in which trend changepoints will be estimated. Defaults to 0.8 for the first 80%. Not used if `changepoints` is specified.|
|yearly.seasonality| | Fit yearly seasonality. Can be 'auto', TRUE, FALSE, or a number of Fourier terms to generate.|
| weekly.seasonality| | Fit weekly seasonality. Can be 'auto', TRUE, FALSE, or a number of Fourier terms to generate.
| daily.seasonality| | Fit daily seasonality. Can be 'auto', TRUE, FALSE, or a number of Fourier terms to generate.|
| holidays| | data frame \|ds\|lower_window \|upper_window\| with columns holiday (character) and ds (date type)and optionally columns lower_window and upper_window which specify a range of days around the date to be included as holidays. lower_window=-2 will include 2 days prior to the date as holidays. Also optionally can have a column prior_scale specifying the prior scale for each holiday.
|seasonality.mode| 'additive' (default) or 'multiplicative'||
|seasonality.prior.scale| |Parameter modulating the strength of the seasonality model. Larger values allow the model to fit larger seasonal fluctuations, smaller values dampen the seasonality. Can be specified for individual seasonalities using add_seasonality. TODO add different priors|
|holidays.prior.scale | |Parameter modulating the strength of the holiday components model, unless overridden in the holidays input.|
|changepoint.prior.scale| | Parameter modulating the flexibility of the automatic changepoint selection. Large values will allow many changepoints, small values will allow few changepoints.|
|mcmc.samples | Integer| if greater than 0, will do full Bayesian inference with the specified number of MCMC samples. If 0, will do MAP estimation.|
|interval.width| |Numeric, width of the uncertainty intervals provided for the forecast. If mcmc.samples=0, this will be only the uncertainty in the trend using the MAP estimate of the extrapolated generative model.
If mcmc.samples>0, this will be integrated over all model parameters,which will include uncertainty in seasonality.|
|uncertainty.samples| | Number of simulated draws used to estimate uncertainty intervals.|
|fit| Boolean| if FALSE the model is initialized but not fit.|
|...| | Additional arguments, passed to \code{\link{fit.prophet}}|

